#!/usr/bin/env node
// Builds everything derived from shared/: golden fixtures + per-platform constants.
//
//   node shared/scripts/generate.mjs          write outputs
//   node shared/scripts/generate.mjs --check  exit 1 if any output is stale (CI)
//
// Sources of truth:
//   shared/reference/chord-layout.js  geometry + palette (from the design handoff)
//   shared/data/tokens.json           UI tokens around the diagram
//   shared/data/chords.json           chord library
//   shared/fixtures/cases.json        extra conformance inputs
//
// To add a platform, write an emitter below and register it in `emitters`.

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const REFERENCE = "shared/reference/chord-layout.js";
const ref = createRequire(import.meta.url)(join(root, REFERENCE));
const referenceSource = readFileSync(join(root, REFERENCE), "utf8");

const readJson = (p) => JSON.parse(readFileSync(join(root, p), "utf8"));
const tokens = readJson("shared/data/tokens.json");
const library = readJson("shared/data/chords.json").chords;
const fixtureCases = readJson("shared/fixtures/cases.json");
const extraCases = fixtureCases.cases;
const invalidCases = fixtureCases.invalidCases ?? [];

const errors = [];
const fail = (msg) => errors.push(msg);

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

for (const [key, hex] of Object.entries(ref.PALETTE)) {
  if (String(tokens.palette[key]).toLowerCase() !== hex.toLowerCase()) {
    fail(`tokens.json palette.${key} is ${tokens.palette[key]}, reference PALETTE.${key} is ${hex}`);
  }
}

// the reference's own validateChord is the rulebook, so data and ports can't disagree about it
function validateChord(where, chord) {
  for (const issue of ref.validateChord(chord)) fail(`${where}: ${issue.path ? `${issue.path} ` : ""}${issue.message}`);
}

const seen = new Set();
for (const { id, ...chord } of library) {
  if (!/^[A-Za-z][A-Za-z0-9]*$/.test(id ?? "")) fail(`chords.json: id "${id}" must be alphanumeric and start with a letter`);
  if (seen.has(id)) fail(`chords.json: duplicate id "${id}"`);
  seen.add(id);
  validateChord(`chords.json ${id}`, chord);
}
for (const c of extraCases) validateChord(`cases.json ${c.id}`, c.chord);
for (const c of invalidCases) {
  if (!ref.validateChord(c.chord).length) fail(`cases.json invalidCases ${c.id}: expected at least one validation issue`);
}

if (errors.length) {
  console.error(errors.map((e) => `  ✗ ${e}`).join("\n"));
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Golden fixtures (platform-neutral)
// ---------------------------------------------------------------------------

const issueRefs = (chord) => ref.validateChord(chord).map(({ code, path }) => ({ code, path }));

function emitGolden() {
  const cases = [
    ...library.map(({ id, ...chord }) => ({ id: `library/${id}`, chord, options: {} })),
    ...extraCases.map((c) => ({ id: `case/${c.id}`, chord: c.chord, options: c.options ?? {} })),
    ...invalidCases.map((c) => ({ id: `invalid/${c.id}`, chord: c.chord, options: c.options ?? {} }))
  ].map((c) => {
    const layout = ref.layoutChord(c.chord, c.options);
    return { ...c, layout, svg: ref.toSvg(layout, 1), description: ref.describeChord(c.chord), issues: issueRefs(c.chord) };
  });
  const doc = {
    $comment: `GENERATED by shared/scripts/generate.mjs from ${REFERENCE} — do not edit. Every platform port must reproduce these layouts (within 1e-9), SVG strings and descriptions (exactly), and validation issues (code and path).`,
    cases
  };
  return { "shared/fixtures/golden.json": JSON.stringify(doc, null, 2) + "\n" };
}

// ---------------------------------------------------------------------------
// Fuzz fixtures: seeded random chords, valid and malformed
// ---------------------------------------------------------------------------

const FUZZ_SEED = 20260914;
const FUZZ_CASES = 400;

function mulberry32(seed) {
  let state = seed >>> 0;
  return () => {
    state = (state + 0x6d2b79f5) >>> 0;
    let t = state;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// FNV-1a 64 over UTF-8, so a port can check a whole SVG against one short string
function fnv1a64(text) {
  let hash = 0xcbf29ce484222325n;
  for (const byte of Buffer.from(text, "utf8")) {
    hash ^= BigInt(byte);
    hash = (hash * 0x100000001b3n) & 0xffffffffffffffffn;
  }
  return hash.toString(16).padStart(16, "0");
}

function emitFuzz() {
  const random = mulberry32(FUZZ_SEED);
  const int = (lo, hi) => lo + Math.floor(random() * (hi - lo + 1));
  const pick = (items) => items[int(0, items.length - 1)];
  const cases = [];
  for (let n = 0; n < FUZZ_CASES; n++) {
    const strings = pick([6, 6, 6, 6, 6, 4, 4, 5, 7, 8, 12, 2, 1, 0, 13]);
    const base = int(0, 22);
    const reach = pick([2, 3, 3, 4, 5, 7, 11, 16]);
    const frets = Array.from({ length: strings }, () => {
      const r = random();
      if (r < 0.14) return -1;
      if (r < 0.28) return 0;
      if (r < 0.31) return pick([-3, -2, 100, 140]);
      return Math.max(1, base + int(0, reach));
    });
    const chord = {};
    if (random() < 0.6) chord.name = `Fuzz ${n}`;
    chord.frets = frets;
    if (random() < 0.7) {
      const length = random() < 0.1 ? int(0, strings + 2) : strings;
      chord.fingers = Array.from({ length }, () => pick([0, 0, 1, 2, 3, 4, 5, 6, -1]));
    }
    if (random() < 0.35) {
      const fretted = frets.filter((f) => f > 0 && f <= ref.M.MAX_FRET);
      const fret = fretted.length && random() < 0.8 ? pick(fretted) : int(0, 30);
      chord.barre = { fret, from: int(-1, strings), to: int(-1, strings) };
      if (random() < 0.6) chord.barre.finger = pick([1, 1, 2, 0, 5, 9]);
    }
    if (random() < 0.15) chord.caption = random() < 0.5 ? "" : `caption ${n}`;
    if (random() < 0.12) {
      chord.tuning = Array.from({ length: random() < 0.8 ? strings : strings + 1 }, (_, i) => (random() < 0.05 ? "" : `S${i}`));
    }
    const options = random() < 0.2 ? { showFingers: false } : {};
    const layout = ref.layoutChord(chord, options);
    cases.push({
      chord,
      options,
      position: layout.position,
      rows: layout.rows,
      strings: layout.strings,
      svgFnv1a64: fnv1a64(ref.toSvg(layout, 1)),
      description: ref.describeChord(chord),
      issues: issueRefs(chord)
    });
  }
  const comment = `GENERATED by shared/scripts/generate.mjs (seed ${FUZZ_SEED}) from ${REFERENCE} — do not edit. Random chords, valid and malformed. Every port must reproduce each case's position, rows, strings, description and issues, and the FNV-1a 64 hash of its SVG.`;
  const body = cases.map((c) => `    ${JSON.stringify(c)}`).join(",\n");
  return { "shared/fixtures/fuzz.json": `{\n  "$comment": ${JSON.stringify(comment)},\n  "cases": [\n${body}\n  ]\n}\n` };
}

// ---------------------------------------------------------------------------
// Swift
// ---------------------------------------------------------------------------

const camel = (s) => s.toLowerCase().replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());
const lowerFirst = (s) => s.charAt(0).toLowerCase() + s.slice(1);
const swiftString = (s) => JSON.stringify(s).replace(/\\u([0-9a-fA-F]{4})/g, "\\u{$1}");
const swiftHeader = (sources) =>
  `// GENERATED by shared/scripts/generate.mjs — do not edit.\n// Sources: ${sources.join(", ")}\n`;

// pull the trailing `// comment` for each key out of the reference so docs follow the numbers
function referenceComments(objectName) {
  const block = new RegExp(`const ${objectName} = \\{([\\s\\S]*?)\\n\\};`).exec(referenceSource)?.[1] ?? "";
  const out = {};
  for (const line of block.split("\n")) {
    const m = /^\s*([A-Za-z_0-9]+):[^/]*(?:\/\/\s*(.*))?$/.exec(line);
    if (m && m[2]) out[m[1]] = m[2].trim();
  }
  return out;
}

const INT_METRICS = new Set(["SPAN", "STRINGS", "MIN_STRINGS", "MAX_STRINGS", "MAX_ROWS", "MAX_FRET", "THUMB"]);

function emitSwiftMetrics() {
  const metricDocs = referenceComments("M");
  const paletteDocs = referenceComments("PALETTE");
  const doc = (text) => (text ? `    /// ${text}\n` : "");
  const metrics = Object.entries(ref.M)
    .map(([k, v]) => `${doc(metricDocs[k])}    public static let ${camel(k)}: ${INT_METRICS.has(k) ? "Int" : "Double"} = ${v}`)
    .join("\n");
  const palette = Object.entries(ref.PALETTE)
    .map(([k, v]) => `${doc(paletteDocs[k])}    public static let ${k} = ${swiftString(v)}`)
    .join("\n");
  return `${swiftHeader([REFERENCE])}
/// Every number in the chord diagram, in the fixed ${ref.M.WIDTH} × ${ref.M.HEIGHT} design space (y down).
public enum ChordMetrics {
${metrics}
}

/// Default diagram colors as sRGB hex.
public enum ChordPalette {
${palette}
}
`;
}

function swiftChordLiteral(chord) {
  const args = [];
  if (chord.name != null) args.push(`name: ${swiftString(chord.name)}`);
  args.push(`frets: [${chord.frets.join(", ")}]`);
  if (chord.fingers) args.push(`fingers: [${chord.fingers.join(", ")}]`);
  if (chord.barre) {
    const b = chord.barre;
    args.push(`barre: Barre(fret: ${b.fret}, from: ${b.from}, to: ${b.to}${b.finger != null ? `, finger: ${b.finger}` : ""})`);
  }
  if (chord.caption != null) args.push(`caption: ${swiftString(chord.caption)}`);
  return `Chord(${args.join(", ")})`;
}

function emitSwiftLibrary() {
  const statics = library
    .map(({ id, ...chord }) => `    public static let ${lowerFirst(id)} = ${swiftChordLiteral(chord)}`)
    .join("\n");
  const entries = library.map(({ id }) => `        Entry(id: ${swiftString(id)}, chord: ${lowerFirst(id)})`).join(",\n");
  return `${swiftHeader(["shared/data/chords.json"])}
public enum ChordLibrary {
    public struct Entry: Identifiable, Hashable, Sendable {
        public let id: String
        public let chord: Chord
    }

${statics}

    /// Every chord in library order.
    public static let all: [Entry] = [
${entries}
    ]
}
`;
}

function emitSwiftTokens() {
  const colorLines = [
    ...Object.entries(tokens.palette).map(([k, v]) => `        public static let ${k} = ${swiftString(v)}`),
    ...Object.entries(tokens.colors).map(([k, v]) => `        public static let ${k} = ${swiftString(v)}`)
  ].join("\n");
  const accents = tokens.accents
    .map((a) => `        Accent(id: ${swiftString(a.id)}, name: ${swiftString(a.name)}, hex: ${swiftString(a.hex)})`)
    .join(",\n");
  const text = Object.entries(tokens.text)
    .map(([k, s]) => {
      const args = [
        `family: .${s.family}`,
        `size: ${s.size}`,
        `weight: ${s.weight ?? 400}`,
        `tracking: ${s.tracking ?? 0}`,
        `lineHeight: ${s.lineHeight ?? "nil"}`,
        `uppercase: ${s.uppercase === true}`
      ];
      return `    public static let ${k} = ChordTextStyle(${args.join(", ")})`;
    })
    .join("\n");
  const layout = Object.entries(tokens.layout)
    .map(([k, v]) => `        public static let ${k}: CGFloat = ${v}`)
    .join("\n");
  return `${swiftHeader(["shared/data/tokens.json"])}
import CoreGraphics

public enum ChordTokens {
    /// sRGB hex; convert with \`Color(chordHex:)\`.
    public enum Colors {
${colorLines}
    }

    public struct Accent: Identifiable, Hashable, Sendable {
        public let id: String
        public let name: String
        public let hex: String
    }

    public static let accents: [Accent] = [
${accents}
    ]

    public static let sansFamilies: [String] = [${tokens.fonts.sans.map(swiftString).join(", ")}]
    public static let monoFamilies: [String] = [${tokens.fonts.mono.map(swiftString).join(", ")}]

    public enum Layout {
${layout}
    }
}

extension ChordTextStyle {
${text}
}
`;
}

// the SwiftUI target only exists on Apple platforms; keep `swift test` working on Linux
function swiftUIOnly(source) {
  const lines = source.split("\n");
  const header = lines.slice(0, 2).join("\n");
  const body = lines.slice(2).join("\n").trim();
  return `${header}\n\n#if canImport(SwiftUI)\n${body}\n#endif\n`;
}

function emitSwift() {
  return {
    "swift/Sources/ChordDiagramCore/Generated/ChordMetrics.generated.swift": emitSwiftMetrics(),
    "swift/Sources/ChordDiagramCore/Generated/ChordLibrary.generated.swift": emitSwiftLibrary(),
    "swift/Sources/ChordDiagram/Generated/ChordTokens.generated.swift": swiftUIOnly(emitSwiftTokens())
  };
}

// ---------------------------------------------------------------------------
// Kotlin
// ---------------------------------------------------------------------------

const KOTLIN_CORE = "kotlin/chord-diagram-core/src/generated/kotlin/com/guitarcharts/chord";
const KOTLIN_COMPOSE = "kotlin/chord-diagram-compose/src/generated/kotlin/com/guitarcharts/chord/compose";

const pascal = (s) => s.charAt(0).toUpperCase() + s.slice(1);
const kotlinString = (s) => JSON.stringify(s).replace(/\$/g, "\\$");
const kotlinDouble = (n) => (Number.isInteger(n) ? `${n}.0` : `${n}`);
const kotlinFloat = (n) => `${n}f`;
const kotlinHeader = (sources) =>
  `// GENERATED by shared/scripts/generate.mjs — do not edit.\n// Sources: ${sources.join(", ")}\n`;
const kdoc = (text, indent) => (text ? `${indent}/** ${text.replace(/\*\//g, "* /")} */\n` : "");

function emitKotlinMetrics() {
  const metricDocs = referenceComments("M");
  const paletteDocs = referenceComments("PALETTE");
  const metrics = Object.entries(ref.M)
    .map(([k, v]) => `${kdoc(metricDocs[k], "    ")}    const val ${k}: ${INT_METRICS.has(k) ? `Int = ${v}` : `Double = ${kotlinDouble(v)}`}`)
    .join("\n");
  const palette = Object.entries(ref.PALETTE)
    .map(([k, v]) => `${kdoc(paletteDocs[k], "    ")}    const val ${k.toUpperCase()}: String = ${kotlinString(v)}`)
    .join("\n");
  return `${kotlinHeader([REFERENCE])}
package com.guitarcharts.chord

/** Every number in the chord diagram, in the fixed ${ref.M.WIDTH} × ${ref.M.HEIGHT} design space (y down). */
object ChordMetrics {
${metrics}
}

/** Default diagram colors as sRGB hex. */
object ChordPalette {
${palette}
}
`;
}

function kotlinChordLiteral(chord) {
  const args = [];
  if (chord.name != null) args.push(`name = ${kotlinString(chord.name)}`);
  args.push(`frets = listOf(${chord.frets.join(", ")})`);
  if (chord.fingers) args.push(`fingers = listOf(${chord.fingers.join(", ")})`);
  if (chord.barre) {
    const b = chord.barre;
    args.push(`barre = Barre(fret = ${b.fret}, from = ${b.from}, to = ${b.to}${b.finger != null ? `, finger = ${b.finger}` : ""})`);
  }
  if (chord.caption != null) args.push(`caption = ${kotlinString(chord.caption)}`);
  return `Chord(${args.join(", ")})`;
}

function emitKotlinLibrary() {
  const vals = library.map(({ id, ...chord }) => `    val ${id}: Chord = ${kotlinChordLiteral(chord)}`).join("\n");
  const entries = library.map(({ id }) => `        Entry(${kotlinString(id)}, ${id}),`).join("\n");
  return `${kotlinHeader(["shared/data/chords.json"])}
package com.guitarcharts.chord

/** The shared chord library. Property names match the ids in chords.json. */
object ChordLibrary {
    data class Entry(val id: String, val chord: Chord)

${vals}

    /** Every chord in library order. */
    val all: List<Entry> = listOf(
${entries}
    )
}
`;
}

function emitKotlinTokens() {
  const argb = (hex) => `Color(0xFF${hex.replace("#", "").toUpperCase()})`;
  const colors = [...Object.entries(tokens.palette), ...Object.entries(tokens.colors)]
    .map(([k, v]) => `        val ${pascal(k)}: Color = ${argb(v)}`)
    .join("\n");
  const accents = tokens.accents
    .map((a) => `        Accent(id = ${kotlinString(a.id)}, name = ${kotlinString(a.name)}, hex = ${kotlinString(a.hex)}),`)
    .join("\n");
  const layout = Object.entries(tokens.layout)
    .map(([k, v]) => `        val ${pascal(k)}: Dp = ${v}.dp`)
    .join("\n");
  const text = Object.entries(tokens.text)
    .map(([k, s]) => {
      const args = [
        `family = ChordTextStyle.Family.${pascal(s.family)}`,
        `size = ${kotlinFloat(s.size)}`,
        `weight = ${s.weight ?? 400}`,
        `tracking = ${kotlinFloat(s.tracking ?? 0)}`,
        `lineHeight = ${s.lineHeight != null ? kotlinFloat(s.lineHeight) : "null"}`,
        `uppercase = ${s.uppercase === true}`
      ];
      return `    val ${pascal(k)}: ChordTextStyle = ChordTextStyle(${args.join(", ")})`;
    })
    .join("\n");
  return `${kotlinHeader(["shared/data/tokens.json"])}
package com.guitarcharts.chord.compose

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

object ChordTokens {
    object Colors {
${colors}
    }

    data class Accent(val id: String, val name: String, val hex: String) {
        val color: Color get() = chordColor(hex)
    }

    val Accents: List<Accent> = listOf(
${accents}
    )

    /** Preferred font families, in order. Android has none of them built in; see ChordFonts. */
    val SansFamilies: List<String> = listOf(${tokens.fonts.sans.map(kotlinString).join(", ")})
    val MonoFamilies: List<String> = listOf(${tokens.fonts.mono.map(kotlinString).join(", ")})

    object Layout {
${layout}
    }
}

object ChordTextStyles {
${text}
}
`;
}

function emitKotlin() {
  return {
    [`${KOTLIN_CORE}/ChordMetrics.kt`]: emitKotlinMetrics(),
    [`${KOTLIN_CORE}/ChordLibrary.kt`]: emitKotlinLibrary(),
    [`${KOTLIN_COMPOSE}/ChordTokens.kt`]: emitKotlinTokens()
  };
}

// ---------------------------------------------------------------------------
// README figures (docs/images)
// ---------------------------------------------------------------------------

const FIGURES = "shared/docs/figures.json";
const ANDROID_REFERENCES = "kotlin/chord-diagram-compose/src/screenshotTestDebug/reference/com/guitarcharts/chord/compose";
const figures = readJson(FIGURES);
const libraryChords = Object.fromEntries(library.map(({ id, ...chord }) => [id, chord]));
const accentsById = Object.fromEntries(tokens.accents.map((a) => [a.id, a]));
const SANS = "Helvetica Neue, Helvetica, Arial, sans-serif";
const MONO = "IBM Plex Mono, ui-monospace, monospace";
const xmlText = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const r2 = (n) => Math.round(n * 100) / 100;
// the diagram's own primitives, without the outer <svg> element
const svgInner = (layout) => ref.toSvg(layout, 1).replace(/^<svg[^>]*>/, "").replace(/<\/svg>$/, "");

function figureChord(value, where) {
  const chord = typeof value === "string" ? libraryChords[value] : value;
  if (!chord) throw new Error(`${FIGURES} ${where}: unknown chord id "${value}"`);
  validateChord(`${FIGURES} ${where}`, chord);
  if (errors.length) throw new Error(errors.join("\n"));
  return chord;
}

function svgDocument(width, height, title, body) {
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}" role="img" aria-label="${xmlText(title)}">` +
    `<title>${xmlText(title)}</title>` +
    `<rect x="0.5" y="0.5" width="${width - 1}" height="${height - 1}" rx="14" fill="${tokens.palette.paper}" stroke="${tokens.colors.rule}"/>` +
    body +
    `</svg>\n`
  );
}

// One ChordCard (diagram, name, caption, optional export link) with the web component's spacing.
const CARD = { width: 174, padX: 14, padTop: 20, padBottom: 18, gap: 12, nameLine: 19, labelGap: 3, captionLine: 13, link: 18 };
const cardHeight = (withLink) =>
  CARD.padTop + ref.M.HEIGHT + CARD.gap + CARD.nameLine + CARD.labelGap + CARD.captionLine + (withLink ? CARD.link : 0) + CARD.padBottom;

function cardSvg(cell, x, y, where) {
  const chord = { ...figureChord(cell.chord, where) };
  if (cell.name != null) chord.name = cell.name;
  if (cell.caption != null) chord.caption = cell.caption;
  const options = { ...(cell.options ?? {}) };
  if (cell.accent) {
    if (!accentsById[cell.accent]) throw new Error(`${FIGURES} ${where}: unknown accent "${cell.accent}"`);
    options.accent = accentsById[cell.accent].hex;
  }
  const layout = ref.layoutChord(chord, options);
  const centerX = r2(x + CARD.width / 2);
  const nameY = y + CARD.padTop + ref.M.HEIGHT + CARD.gap + 15;
  const captionY = nameY + CARD.labelGap + CARD.captionLine + 1;
  const parts = [
    `<g transform="translate(${r2(x + CARD.padX)} ${r2(y + CARD.padTop)})">${svgInner(layout)}</g>`,
    `<text x="${centerX}" y="${r2(nameY)}" text-anchor="middle" font-family="${SANS}" font-size="15" font-weight="600" fill="${tokens.colors.name}">${xmlText(layout.name)}</text>`,
    `<text x="${centerX}" y="${r2(captionY)}" text-anchor="middle" font-family="${MONO}" font-size="10" letter-spacing="0.8" fill="${tokens.palette.muted}">${xmlText(layout.caption.toUpperCase())}</text>`
  ];
  if (cell.download) {
    const label = `${cell.download} ↓`.toUpperCase();
    const linkY = captionY + CARD.link;
    const width = label.length * (9.5 * 0.6 + 0.76);
    parts.push(
      `<text x="${centerX}" y="${r2(linkY)}" text-anchor="middle" font-family="${MONO}" font-size="9.5" letter-spacing="0.76" fill="${tokens.palette.muted}">${xmlText(label)}</text>`,
      `<rect x="${r2(centerX - width / 2)}" y="${r2(linkY + 3)}" width="${r2(width)}" height="1" fill="${tokens.colors.underline}"/>`
    );
  }
  return parts.join("");
}

function gridFigure(id, grid) {
  const PAD = 24, GAP_X = 4, GAP_Y = 8;
  const withLink = grid.cells.some((c) => c.download);
  const rows = Math.ceil(grid.cells.length / grid.columns);
  const width = PAD * 2 + grid.columns * CARD.width + (grid.columns - 1) * GAP_X;
  const height = PAD * 2 + rows * cardHeight(withLink) + (rows - 1) * GAP_Y;
  const body = grid.cells
    .map((cell, i) =>
      cardSvg(cell, PAD + (i % grid.columns) * (CARD.width + GAP_X), PAD + Math.floor(i / grid.columns) * (cardHeight(withLink) + GAP_Y), `grids.${id}[${i}]`)
    )
    .join("");
  return svgDocument(width, height, grid.title, body);
}

// A large diagram with callouts whose leader lines point at the real primitives.
function anatomyFigure(spec) {
  const chord = figureChord(spec.chord, "anatomy");
  const layout = ref.layoutChord(chord);
  const S = 2.6, W = 860, TOP = 34;
  const gridCenter = (ref.stringX(0) + ref.stringX(ref.M.STRINGS - 1)) / 2;
  const dx = W / 2 - gridCenter * S;
  const X = (x) => r2(dx + x * S);
  const Y = (y) => r2(TOP + y * S);
  const leftEdge = r2(dx - 34);
  const rightEdge = r2(dx + (ref.stringX(ref.M.STRINGS - 1) + ref.M.DOT_R) * S + 70);

  const find = (list, id) => {
    const hit = list.find((p) => p.id === id);
    if (!hit) throw new Error(`${FIGURES} anatomy: chord has no "${id}" to label`);
    return hit;
  };
  const mute = find(layout.lines, "mute");
  const open = find(layout.circles, "open");
  const dot = find(layout.circles, "dot");
  const barre = find(layout.rects, "barre");
  const position = find(layout.texts, "position");
  const stringOf = (x) => Math.round((x - ref.M.LEFT) / ref.M.SPACING);
  const barreIn = chord.barre;

  const callout = (side, targetX, targetY, title, detail) => {
    const labelX = side === "left" ? leftEdge : rightEdge;
    const lineFrom = side === "left" ? labelX + 10 : labelX - 10;
    const anchor = side === "left" ? "end" : "start";
    return (
      `<line x1="${lineFrom}" y1="${targetY}" x2="${targetX}" y2="${targetY}" stroke="${tokens.palette.line}" stroke-width="1"/>` +
      `<circle cx="${targetX}" cy="${targetY}" r="2.6" fill="${tokens.palette.ink}"/>` +
      `<text x="${labelX}" y="${r2(targetY - 5)}" text-anchor="${anchor}" font-family="${MONO}" font-size="11" letter-spacing="1.4" fill="${tokens.colors.link}">${xmlText(title)}</text>` +
      `<text x="${labelX}" y="${r2(targetY + 14)}" text-anchor="${anchor}" font-family="${MONO}" font-size="12" fill="${tokens.colors.body}">${xmlText(detail)}</text>`
    );
  };

  const parts = [`<g transform="translate(${r2(dx)} ${TOP}) scale(${S})">${svgInner(layout)}</g>`];
  parts.push(
    callout("left", r2(X(Math.min(mute.x1, mute.x2)) - 6), Y(ref.M.MARKER_Y), "MUTED STRING", `frets[${stringOf(mute.x1 + ref.M.MUTE_HALF)}] = -1`),
    callout("left", r2(X(position.x - 20) - 4), Y(position.y), "FRET WINDOW", `starts at fret ${layout.position}`),
    callout("right", r2(X(open.cx + open.r) + 6), Y(open.cy), "OPEN STRING", `frets[${stringOf(open.cx)}] = 0`),
    callout("right", r2(X(dot.cx + dot.r) + 6), Y(dot.cy), "FINGER NUMBER", `fingers[${stringOf(dot.cx)}] = ${chord.fingers[stringOf(dot.cx)]}`),
    callout("right", r2(X(barre.x + barre.w) + 6), Y(barre.y + barre.h / 2), "BARRE", `fret ${barreIn.fret}, strings ${barreIn.from}–${barreIn.to}`)
  );

  const namesY = Y(ref.M.HEIGHT) + 24;
  ["E", "A", "D", "G", "B", "e"].forEach((n, i) =>
    parts.push(`<text x="${X(ref.stringX(i))}" y="${r2(namesY)}" text-anchor="middle" font-family="${MONO}" font-size="13" fill="${tokens.palette.muted}">${n}</text>`)
  );
  const nameY = namesY + 42;
  parts.push(
    `<text x="${X(gridCenter)}" y="${r2(nameY)}" text-anchor="middle" font-family="${SANS}" font-size="22" font-weight="600" fill="${tokens.colors.name}">${xmlText(layout.name)}</text>`,
    `<text x="${X(gridCenter)}" y="${r2(nameY + 22)}" text-anchor="middle" font-family="${MONO}" font-size="12" letter-spacing="1" fill="${tokens.palette.muted}">${xmlText(layout.caption.toUpperCase())}</text>`
  );
  return svgDocument(W, Math.ceil(nameY + 48), spec.title, parts.join(""));
}

function emitDocs() {
  const out = {};
  for (const [id, grid] of Object.entries(figures.grids)) out[`docs/images/${id}.svg`] = gridFigure(id, grid);
  out["docs/images/anatomy.svg"] = anatomyFigure(figures.anatomy);

  // the exact file ChordExporter writes, byte for byte
  const exportChord = figureChord(figures.export.chord, "export");
  out[`docs/images/export-${figures.export.chord.toLowerCase()}.svg`] = ref.toSvg(ref.layoutChord(exportChord), figures.export.scale);

  for (const [name, key] of Object.entries(figures.android)) {
    const [folder, fn] = key.split("/");
    const dir = join(root, ANDROID_REFERENCES, folder);
    const matches = existsSync(dir) ? readdirSync(dir).filter((f) => f.startsWith(`${fn}_`) && f.endsWith(".png")) : [];
    if (matches.length !== 1) {
      throw new Error(`${FIGURES} android.${name}: expected 1 screenshot reference for ${key}, found ${matches.length}. Run ./gradlew :chord-diagram-compose:updateDebugScreenshotTest and delete stale references.`);
    }
    out[`docs/images/android/${name}.png`] = readFileSync(join(dir, matches[0]));
  }
  return out;
}

// ---------------------------------------------------------------------------
// JavaScript (@lightsonfire/chord-diagram-core, shared by React and React Native)
// ---------------------------------------------------------------------------

const JS_CORE = "js/core/src/generated";
const jsHeader = (sources) =>
  `// GENERATED by shared/scripts/generate.mjs — do not edit.\n// Sources: ${sources.join(", ")}\n`;
const jsKey = (k) => (/^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k));
const jsLiteral = (value) =>
  Array.isArray(value)
    ? `[${value.map(jsLiteral).join(", ")}]`
    : value !== null && typeof value === "object"
      ? `{ ${Object.entries(value).map(([k, v]) => `${jsKey(k)}: ${jsLiteral(v)}`).join(", ")} }`
      : JSON.stringify(value);

// JavaScript runs the reference itself instead of a port: swap its CommonJS tail for ES exports.
function emitJsReference() {
  const tail = /\nif \(typeof module !== "undefined"\) \{\n\s*module\.exports = \{([^}]*)\};\n\}\n?$/.exec(referenceSource);
  if (!tail) throw new Error(`${REFERENCE}: expected the file to end with its module.exports block`);
  const names = tail[1].split(",").map((n) => n.trim()).filter((n) => n && n !== "CHORDS");
  return `// @ts-nocheck\n${jsHeader([REFERENCE])}// Plain JavaScript; typed by ../layout.ts.\n\n${referenceSource.slice(0, tail.index)}\nexport { ${names.join(", ")} };\n`;
}

function emitJsLibrary() {
  if (library.some(({ id }) => id === "all")) throw new Error(`chords.json: id "all" is reserved for ChordLibrary.all`);
  const chords = library.map(({ id, ...chord }) => `  ${id}: ${jsLiteral(chord)},`).join("\n");
  return `${jsHeader(["shared/data/chords.json"])}
import type { Chord } from "../types.js";

export type ChordId = ${library.map(({ id }) => JSON.stringify(id)).join(" | ")};

export interface ChordLibraryEntry {
  readonly id: ChordId;
  readonly chord: Chord;
}

const chords = {
${chords}
} satisfies Record<ChordId, Chord>;

/** The shared chord library. Keys match the ids in chords.json; \`all\` lists every chord in library order. */
export const ChordLibrary: { readonly [K in ChordId]: Chord } & { readonly all: readonly ChordLibraryEntry[] } = {
  ...chords,
  all: (Object.keys(chords) as ChordId[]).map((id) => ({ id, chord: chords[id] })),
};
`;
}

function emitJsTokens() {
  const { $comment, ...rest } = tokens;
  const body = JSON.stringify(rest, null, 2).replace(/^(\s*)"([A-Za-z_$][\w$]*)":/gm, "$1$2:");
  return `${jsHeader(["shared/data/tokens.json"])}
/** Colors, accents, fonts, type and spacing around the diagram. Colors are sRGB hex, sizes px (dp on native), tracking and line height em. */
export const ChordTokens = ${body} as const;
`;
}

function emitJs() {
  return {
    [`${JS_CORE}/reference.ts`]: emitJsReference(),
    [`${JS_CORE}/library.ts`]: emitJsLibrary(),
    [`${JS_CORE}/tokens.ts`]: emitJsTokens()
  };
}

// ---------------------------------------------------------------------------
// Write / check
// ---------------------------------------------------------------------------

const emitters = { golden: emitGolden, fuzz: emitFuzz, swift: emitSwift, kotlin: emitKotlin, js: emitJs, docs: emitDocs };
const outputs = Object.assign({}, ...Object.values(emitters).map((emit) => emit()));
const check = process.argv.includes("--check");
const stale = [];

for (const [path, content] of Object.entries(outputs)) {
  const abs = join(root, path);
  const next = Buffer.isBuffer(content) ? content : Buffer.from(content, "utf8");
  let current = null;
  try {
    current = readFileSync(abs);
  } catch {}
  if (current && current.equals(next)) continue;
  stale.push(path);
  if (!check) {
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, next);
  }
}

if (check && stale.length) {
  console.error(`Generated files are stale — run \`npm run generate\`:\n${stale.map((p) => `  ${p}`).join("\n")}`);
  process.exit(1);
}
console.log(stale.length ? `${check ? "stale" : "wrote"}:\n${stale.map((p) => `  ${p}`).join("\n")}` : "generated files up to date");
